# Generated by Django 6.0.3 on 2026-04-30 17:26

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_estudiante', models.CharField(max_length=150, verbose_name='Nombre del estudiante')),
                ('identificacion', models.CharField(max_length=15, verbose_name='Identificación')),
                ('asignatura', models.CharField(max_length=100, verbose_name='Asignatura')),
                ('nota1', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Nota 1')),
                ('nota2', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Nota 2')),
                ('nota3', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Nota 3')),
                ('promedio', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=4, verbose_name='Promedio')),
            ],
            options={
                'verbose_name': 'Calificación',
                'verbose_name_plural': 'Calificaciones',
                'ordering': ['nombre_estudiante', 'asignatura'],
            },
        ),
    ]
